import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-white p-[20px] w-full">
          <Link href={"/"} className="mr-[10px] no-underline">
            홈
          </Link>
          <Link href={"/list"} className="mr-[10px] no-underline">
            List
          </Link>
        </nav>
        <div className="flex justify-center items-center h-screen bg-slate-500">
          {children}
        </div>
      </body>
    </html>
  );
}
